### ISSUE TITLE
Join Coden on GitHub

### ISSUE THREAD

**Issue by rahmanharoon** [CodenCommunity/Support#12]
# Request to Join Coden on GItHub

#### Why do you hope to be one of us? 
> I like to be part of open source community and looking forward to contribute
---
> Add Ons (optional):
#### Where did you find us?
> From a friend

#### What do you like about this community?
> No response

**Comment by LeeRenJie** [comment]
@rahmanharoon I can't seem to find you on our discord server. Please join the server and join the discussion there too! https://discord.gg/yUebBfg2xU

**Comment by rahmanharoon** [comment]
I have joined the discord channel now

**Comment by LeeRenJie** [comment]
Feel free to close this issue after joining Coden on GitHub! Happy to have you here!
