### ISSUE TITLE
Join Coden on GitHub

### ISSUE THREAD

**Issue by SugatoBagchi** [CodenCommunity/Support#13]
**Name: Sugato Bagchi**

**Discord Username: DemonzTimexs#6027**

**Why do you hope to be one of us?**

To be a part of this community and learn/contribute together.

**Where did you find us?**

Friends

**What do you like about this community?**

The open community work & idea.

**Comment by LeeRenJie** [comment]
Hey @SugatoBagchi thanks for applying. But I cant seem to find you on our discord server. Feel free to join us at discord before applying to join here!
Join here https://discord.gg/yUebBfg2xU

**Comment by SugatoBagchi** [comment]
> Hey @SugatoBagchi thanks for applying. But I cant seem to find you on our discord server. Feel free to join us at discord before applying to join here!
> Join here https://discord.gg/yUebBfg2xU

Hi @LeeRenJie 
I joined the server. Request you to check now.

Thank you.

**Comment by LeeRenJie** [comment]
> > Hey @SugatoBagchi thanks for applying. But I cant seem to find you on our discord server. Feel free to join us at discord before applying to join here!
> > Join here https://discord.gg/yUebBfg2xU
> 
> Hi @LeeRenJie
> I joined the server. Request you to check now.
> 
> Thank you.

Hey @SugatoBagchi 
Happy to see you in. 
Feel free to close this issue after you have accepted the invitation :)
