### ISSUE TITLE
Join Coden on GitHub

### ISSUE THREAD

**Issue by AvidCoder101** [CodenCommunity/Support#17]
# Request to Join Coden on GItHub

#### Why do you hope to be one of us? 
To contribute
---

#### What do you like about this community?
they have a variety of repos

**Comment by LeeRenJie** [comment]
Hey there @AvidCoder101 , you have to be in our discord channel in order to get updates and be a part of our community. Please join us through: 

 https://discord.gg/yUebBfg2xU
