### ISSUE TITLE
Join Coden on GitHub

### ISSUE THREAD

**Issue by jvloo** [CodenCommunity/Support#3]
# Request to Join Coden GitHub Community Organisation.
---

#### Why do you hope to be one of us? 
- Would like to join projects and contribute as part of the community
- Make more dev friends and learn from others

> Add Ons (optional):

**Comment by LeeRenJie** [comment]
@jvloo feel free to close the issue after joining!😄

**Comment by jvloo** [comment]
@LeeRenJie Hi, I think I don't receive any invitation of join Coden GitHub. Sorry for the late reply as I was busy recently 😅

**Comment by jvloo** [comment]
@LeeRenJie Hi, sorry for late reply as I was busy recently.
May I request for a new invitation? I think I missed it. Thanks!! 😅

**Comment by LeeRenJie** [comment]
> @LeeRenJie Hi, sorry for late reply as I was busy recently.
> May I request for a new invitation? I think I missed it. Thanks!! 😅

Sure no worries!
