### ISSUE TITLE
Join Coden on GitHub

### ISSUE THREAD

**Issue by CheeMinHao** [CodenCommunity/Support#4]
# Request to Join Coden GitHub Community Organisation.
---

#### Why do you hope to be one of us? 
> Wanted to further grow as a developer/programmer regardless of experiencing working in a team or for knowledge

> network with people and gain insights, and to hopefully one day share mine to others as well

> To do things that which I do not have a clear timeline about (e.g. making a discord bot) 

> Add Ons (optional):

Through The Hacker's Community's Discord

The scale of it being moderate, therefore easier to engage

**Comment by LeeRenJie** [comment]
@CheeMinHao feel free to close the issue after joining!
